### ISSUE TITLE
rebar3 plugin

### ISSUE THREAD

**Issue by tsloughter** [j14159/mlfe#1]
I'm excited to play around and hopefully help with mlfe. To start I began the process of creating a rebar3 plugin :) https://github.com/tsloughter/rebar_prv_mlfe

On a side note, I'd suggest either adding `rebar.lock` to the `.gitignore` of `mlfe` or just committing it even though it is empty. Hmm, maybe rebar3 should stop outputting it if it is empty though... I'll think about that :)

Anyway, just letting you know, so feel free to close this issue after reading it.

**Comment by lpil** [comment]
I think there is more value in committing it as in future it may contain something.

Thanks for the work on the plugin!

**Comment by j14159** [comment]
@tsloughter thanks for the rebar plugin!  I'll add `rebar.lock` for now, can't see any reason not to :)
