### ISSUE TITLE
mlfe:file/{1,2}

### ISSUE THREAD

**Issue by tuncer** [j14159/mlfe#14]
Mirroring `compile:file{1,2}`, there ought to be `mlfe:file/{1,2}`. I intend to add this as soon as time permits.

**Comment by yurrriq** [comment]
:+1: In LFE we have `lfe_comp:file{1,2}`.

**Comment by tuncer** [comment]
Patch: #17

**Comment by tuncer** [comment]
Resolved via merge of #17.
