### ISSUE TITLE
scanner.erl

### ISSUE THREAD

**Issue by tuncer** [j14159/mlfe#15]
I think `scanner.erl` should be renamed because it's very likely to clash with an already existing `scanner.beam`. It looks internal, so how about renaming to `mlfe_scanner`. Alternatively, and as a way to denote internal modules, maybe we should use `mlfe_prv_scanner` and probably rename other internal modules as well.

Thoughts?

**Comment by yurrriq** [comment]
`_prv_` often means provider in rebar3 land. Maybe `mlfe_scan`.

**Comment by tuncer** [comment]
`mlfe_scan.erl` is already generated from `mlfe_scan.xrl`. I'm not sure rebar3 has or should have the monopoloy on `prv_` since I've seen that used before rebar3 existed. `mlfe_int_` would work as well, as long as there's no module dealing exclusively with integers.

**Comment by tuncer** [comment]
The patch to rename (without `_prv_`) is here: #16.

**Comment by yurrriq** [comment]
Right, I didn't mean to suggest a monopoly. `prv_` also conveys "private" to me. `mlle_scanner` (#16) sounds good.

**Comment by tuncer** [comment]
Resolved via merge of #16.
