### ISSUE TITLE
Rename call_erlang keyword

### ISSUE THREAD

**Issue by lpil** [j14159/mlfe#2]
Hello!

This keyword seems oddly named as it seems one would use it to call any BEAM language, not just Erlang. Seems odd to use this name to call Elixir or LFE.

Alternatives:

- call
- call_native
- call_unsafe
- call_beam

**Comment by rpip** [comment]
Yes, the `call_erlang` is a bit confusing as @lpil pointed out.

Also, I think we can learn from how other BEAM languages do Erlang FFI. Say you want to call `lists.seq/2` to generate a sequence of integers from 1 to 10. In Elixir, you would write `:lists.seq(1,10)`. And in LFE, a Lisp on the BEAM, you write `(lists:seq 1 10)`. With this, one can still use the MLFE `match` to check the FFI return values: 

```
match :a_module.a_function([3, "different", "arguments"]) with
   (ok, _) -> :ok
 | (error, _) -> :error
```

**Comment by lpil** [comment]
In Elixir `:lists.seq(1,10)` isn't FFI, it's just a normal function call. It looks different because the module atom is `:lists` instead of `:"Elixir.List"`, but it's just syntactic sugar to prevent the user from having to type `:Elixir.` all the time.

Same in LFE, but they don't even have the sugar.

**Comment by lpil** [comment]
Now that I think about it the only difference between this Lang and other Langs on the BEAM is type safety, so a name that expresses the lack of safety seems sensible.

**Comment by rpip** [comment]
Indeed, the type safety of MLFE means the Erlang interop may not be like typical interpretations of language interop, especially since the FFI will not support return of values typed as term() or any(). 

I'm not sure I understand your explanation of how `:lists.seq(1,10)` works in Elixir because `:"Elixir.List"` maps to the `List` module.

**Comment by lpil** [comment]
It's the other way round. `List` is an alias for `:"Elixir.List"`, so the macro expands to the same atom style function call as `:lists.seq(1,10)`. There is no special syntax for calls to Erlang. :)

**Comment by j14159** [comment]
Yeah, the intention was to highlight the "you're leaving the type-safe area here, beware" with the FFI for now.  

I'd like to enable `module.function(args)` calls to Erlang at some point but that will require working directly with dialyzer, yielding some other issues e.g.:  should the typer have enough knowledge to understand that when dialyzer yields `{'A', 1} | integer()` and `type t = int | A int` is in scope, the Erlang code is returning an instance of `t`?  This mixes typing and knowledge from the code generator, restricting changes to both.  Without this knowledge, if dialyzer yields the union `{'A', 1} | integer()` for a particular type and the MLFE code in question has `type t = int | A int` in scope, it would still require the pattern matches that `call_erlang` does now.

Where I'm going with this is I'd _like_ to have a briefer solution but I'm not 100% settled on what it will look like and require :)  Absolutely open to ideas.

**Comment by lpil** [comment]
There problem I'm raising here is not the brevity of the keyword, but the assumption that is calling Erlang. The origin of the BEAM bytecode providing the function is unknown, if it is bytecode at all.

It would be better I think for the keyword to make a statement about the behaviour of these calls instead of a statement about an assumption about the data passed to the keyword.

**Comment by j14159** [comment]
That's fair.  I think `call` is sufficient here, want to submit a PR?

**Comment by yurrriq** [comment]
+1 to `call_unsafe`, since it's more descriptive, while general.

**Comment by j14159** [comment]
My concern with `call_unsafe` is that it sounds more like "please don't use the type checker" rather than "call something not MLFE".

**Comment by yurrriq** [comment]
Ah I see... I don't like `native`, because to me that means C or something. `beam` seems maybe too ambiguous. +1 for just `call` then. Exciting project btw. I'm looking forward to following along and maybe contributing.

**Comment by j14159** [comment]
Great, thanks!  (both for the feedback so far and future participation).

**Comment by imetallica** [comment]
@j14159 This is not directly related to this issue at all, but I want to make a suggestion: when interfacing with foreign code (either, Erlang, Elixir, LFE...) we do it via ports?

Something in the likes of Elm, that you can only send/receive pre-defined types.
More information here: http://guide.elm-lang.org/interop/javascript.html

**Comment by lpil** [comment]
Ports are already a thing in the Erlang ecosystem, so we would need to pick another name to avoid confusion.

**Comment by j14159** [comment]
@imetallica you'd like a stricter FFI construct that specifies the types it accepts and automatically checks them?  E.g. (without renaming as discussed above) instead of:

    call_erlang :module :function [x, y, z] with
        i, is_integer i -> make_i_a_string i

you want something like:

    make_i_a_string (call_erlang[int] :module :function [x, y, z])

I don't really like the above syntax but the implication is that the second form knows it has to add a `is_integer` check on the returned value.  Any way I look at it this will require new syntax.  I don't have any particular problem with it beyond what @lpil has raised except for the fact that we'd still need the former for dealing with any sort of union and it's quite common to deal with those in regular Erlang code.  Also if we're continuing this conversation, let's move it to a different issue please :)

**Comment by tuncer** [comment]
@j14159, `call` is fine, so would be `erl` if I had to make a suggestion. While a beam file may be the result of an Elixir or LFE input file, it's always an Erlang (erl) beam file, so I don't think it would be wrong to use `erl`.  The word `call` can be misleading, given Erlang's message passing architecture, but it's not that ambiguous.

**Comment by tuncer** [comment]
@j14159, so should we name it `call` or `erl`? I would prefer `erl` as explained above, if there's no objection. Haskell has `ccall`, so we could consider `ecall`, but I still think `erl` is long enough for something that might be used a lot.

**Comment by yurrriq** [comment]
+1 for `call`

**Comment by j14159** [comment]
A thought:  what about `beam`?  very generic, just calling functions in other beam files.

**Comment by yurrriq** [comment]
Could you call compiled MLFE code via `beam` too? If not, then :-1: `beam`.

**Comment by tuncer** [comment]
It's all beam modules, so we're not trying to shorten it to 3 (erl), then `beam` is a good alternative and makes sense because it's calling compiled code.

**Comment by tuncer** [comment]
@j14159, what's your opinion on eventually introducing a symbol for this?
