### ISSUE TITLE
Union type as ADT argument

### ISSUE THREAD

**Issue by danabr** [j14159/mlfe#37]
The following test case fails:

``` erlang
union_type_as_adt_arg_test() ->
    Code = "module adt\n\n"
           "type union = int | atom\n\n"
           "type t = Union union\n\n"
           "make () = Union 1",
    ?assertMatch({ok, _}, module_typ_and_parse(Code)).
```

Error:

``` erlang
{error, {cannot_unify,adt,7,  {adt,"union",[],[]}, t_int}}
```

It seems like the knowledge about what members are in the union got lost along the way.

This is the line reporting the error: https://github.com/j14159/mlfe/blob/master/src/mlfe_typer.erl#L557

**Comment by j14159** [comment]
I wonder if this is similar to #34 - wouldn't surprise me if we could simplify then handling of ADTs and their unification while solving both, it's a bit heavy-handed at the moment.  I'm going to try to find some time to sort out #25 over the next week (I suspect it's just a case of furthering generalization) and then tackle this (unless it's already solved by then ;) )

**Comment by danabr** [comment]
I have a prototypical fix here: https://github.com/j14159/mlfe/compare/master...danabr:fix/complex-types

I say "prototypical", because the code needs cleanup, and I'm not sure I should do type lookup like this. It also happens to fix the example in #34, but there are more complex ways to use aliases than that example which I'm sure will break even with this simple fix.

**Comment by danabr** [comment]
I've updated the complex-types branch with something that works even for type aliases and type unions.

However, there is something weird going on. `unify_adt` expects two cells as its first arguments, but there are occasions when it gets something that is not a cell. You can see this by removing the "`is_pid(C2)` test and running the tests.

**Comment by j14159** [comment]
Closing due to PR #49
