### ISSUE TITLE
OTP versions supported officialy?

### ISSUE THREAD

**Issue by NobbZ** [j14159/mlfe#4]
I've seen in the README.md that there is only “official” support for 18.x because thats what you use @j14159. Personally I have to handle multiple versions on my system and swap back and forth all the time, and as such like to try to maintain compatibility in a given range. I already have an internal project which I have to keep compatible from 16B3 to current, but I do hope beeing able to drop 16 before years end.

Also I am trying to set up travis on my fork and wanted to know which versions of erlang I shall test against.

The current version does compile against the latest minor release of 17, 18 and 19, where 17 fails during compilation phase and 18 and 19 both pass all tests, but fail in dialyzer phase. For 17 there weren't even a dialyzer run, because of known trouble with modules generated from `xrl` and `yrl` files before OTP 18.

I can reproduce the exact same behaviour on my local system.

From what I have observed on my system and at travis, I'd guess supported range for now should be 18 and 19, while the tests should be run on 18.2, 18.3 and 19.0 at least, dropping 18.2 as soon 19.1 has been released. But I will follow what ever you suggest here.

I will do a WIP-PR in a couple of minutes.

**Comment by j14159** [comment]
@NobbZ thanks for looking into this!  Iirc the dialyzer errors are due to a couple of things I should simply add to an ignore file (bad debugging helpers and a function generated by leex).  I think the range of versions you suggest (18.2, 18.3, and 19) are fine and travis integration is a good idea.

I had not used `rebar3 xref` before but it looks like it's throwing warnings on a lot of functions from the modules generated by leex and yecc.  Easy way to handle this or skip xref?  I'm open to suggestions.

**Comment by NobbZ** [comment]
I already looked into this, and I can configure them easily away, at least the ones I can identify as leex and yecc related. Maybe one should take a deeper look into the remaining ones?

I'm only online by mobile right now, so I can't look as deep as I wish, but I can do that deeper look when I am back home in about 4 hours.

Also as far as I can remember there is a dialyzer complaint in 19, about impossible matches. I am not sure why that one doesn't happen in 18… Might be related to the dialyzer changes regarding maps.

Also in the meantime another question has come to my mind… Warnnings as Warnings or Warnings as Errors? There are a lot of unused variable warnings to fix… But they should get fixed either way ;)

**Comment by j14159** [comment]
I agree the other warnings should be fixed either way.  If the leex and yecc warnings can be configured away for xref, I'm all for including it as part of the travis build and the other xref warnings I can squash pretty quickly unless they're added to your PR.

I don't use an awful lot of maps (iirc just in variable renaming during AST generation) but it's possible the way I'm using them is throwing errors for R19 I can probably take a look this weekend.

Let me know when you're happy with your PR (and our discussion) and I'll merge it and setup travis integration for the master branch this weekend.
