### ISSUE TITLE
Community?

### ISSUE THREAD

**Issue by ericbmerritt** [j14159/mlfe#9]
I wonder if you plan to make a mailinglist/irc channel or some such to talk about the language. I and a few other people are very interested in discussing features and the like, but issues seem to be the wrong place to do it.

**Comment by yurrriq** [comment]
:+1: for an IRC channel

**Comment by j14159** [comment]
I'm fine with either irc or a google group provided the same code of conduct is applied.  I haven't set anything up yet as I have limited time to moderate either.  There's also still an outstanding possible name change :)

**Comment by j14159** [comment]
I've setup `#mlfe` on freenode for now and will close this issue once I've added that to the main `README` here.

**Comment by j14159** [comment]
Reference to `#mlfe` on freenode added to the README.  I've claimed the channel and set the topic to the effect of discussion of the language and getting help along with reference to the code of conduct set in this repository.  I'll close this issue for now but we can revisit it later if anyone has strong opinions about mailing lists/Google groups.
